# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  sonarr:
    extends:
      file: ../compose.base.yaml
      service: exposed-service
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - tv-collector
      - torrents
      - usenet
    volumes:
      - ./volumes/sonarr_config/:/config/
      - ${NASCOMPOSE_DATA?}/:/data/
    labels:
      traefik.http.routers.sonarr.middlewares: authelia@file

networks:
  tv-collector:
    name: tv-collector
  reverse-proxy:
    external: true
  torrents:
    external: true
  usenet:
    external: true
  media-player:
    external: true
