name: tv-collector

services:
  sonarr:
    hostname: sonarr
    image: lscr.io/linuxserver/sonarr
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - reverse-proxy
      - tv-collector
      - torrents
      - usenet
    volumes:
      - ${NASCOMPOSE_SERVICES?}/tv-collector/volumes/sonarr_config/:/config/
      - ${NASCOMPOSE_DATA?}/:/data/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.middlewares: authelia@file

networks:
  tv-collector:
    name: tv-collector

  reverse-proxy:
    external: true
  torrents:
    external: true
  usenet:
    external: true
  media-player:
    external: true
