name: Torrents

services:
  qbittorrent:
    hostname: qbittorrent
    image: hotio/qbittorrent
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
      VPN_ENABLED: true
      VPN_LAN_NETWORK: 192.168.0.0/23
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    networks:
      - reverse-proxy
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${NASCOMPOSE_SERVICES?}/torrents/volumes/qbittorrent_config/:/config/
      - ${NASCOMPOSE_DATA?}/torrents/:/data/
      # Configuration
      - ${NASCOMPOSE_SERVICES?}/torrents/config/set_port.sh:/bin/set_port.sh:ro
      - ${NASCOMPOSE_SERVICES?}/torrents/config/01-natpmp-install:/etc/cont-init.d/01-natpmp-install:ro
      - ${NASCOMPOSE_SERVICES?}/torrents/config/98-gateway-setup:/etc/cont-init.d/98-gateway-setup:ro
      - ${NASCOMPOSE_SERVICES?}/torrents/config/99-cron-start:/etc/cont-init.d/99-cron-start:ro
      # Secrets
      - ${NASCOMPOSE_SERVICES?}/torrents/secrets/wg0.conf:/config/wireguard/wg0.conf:ro
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.qbittorrent.middlewares: authelia@file

  cross-seed:
    hostname: cross-seed
    image: crossseed/cross-seed
    user: ${NASCOMPOSE_UID?}:${NASCOMPOSE_GID?}
    networks:
      - torrents
      - indexer
      - reverse-proxy
    volumes:
        - ${NASCOMPOSE_SERVICES?}/torrents/volumes/cross-seed_config/:/config/
        - ${NASCOMPOSE_SERVICES?}/torrents/volumes/qbittorrent_config/data/BT_backup/:/torrents/:ro
        - ${NASCOMPOSE_DATA?}/torrents/watch/:/cross-seeds/
    command: daemon
    restart: unless-stopped

  qbitmanage:
    hostname: qbitmanage
    image: hotio/qbitmanage
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
      QBT_SCHEDULE: 30
      QBT_WIDTH: 170
    networks:
      - torrents
      - reverse-proxy
    volumes:
      - ${NASCOMPOSE_SERVICES?}/torrents/volumes/qbitmanage_config/:/config/
      - ${NASCOMPOSE_DATA?}/torrents/:/data/
      - ${NASCOMPOSE_SERVICES?}/torrents/volumes/qbittorrent_config/data/BT_backup/:/torrents/:ro

networks:
  torrents:
    name: torrents

  reverse-proxy:
    external: true
  indexer:
    external: true
