name: Torrents

services:
  transmission:
    hostname: transmission
    image: haugene/transmission-openvpn
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
      OPENVPN_PROVIDER: ${NASCOMPOSE_TRANSMISSION_VPNPROVIDER?}
      OPENVPN_CONFIG: ${NASCOMPOSE_TRANSMISSION_VPNREGION?}
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
      LOCAL_NETWORK: 192.168.0.0/16
    cap_add:
      - NET_ADMIN
    networks:
      - reverse-proxy
      - torrents
    dns:
      # Work around DNS blocks in various regions
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ${NASCOMPOSE_SERVICES?}/torrents/volumes/transmission_config/:/config/
      - ${NASCOMPOSE_DATA?}/torrents/:/data/
    secrets:
      - source: transmission_vpn_creds
        target: openvpn_creds
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.services.transmission.loadbalancer.server.port: 9091
      traefik.http.routers.transmission.middlewares: authelia@file

  qbittorrent:
    hostname: qbittorrent
    image: hotio/qbittorrent
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
      VPN_ENABLED: true
      VPN_LAN_NETWORK: 192.168.0.0/23
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    networks:
      - reverse-proxy
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${NASCOMPOSE_SERVICES?}/torrents/volumes/qbittorrent_config/:/config/
      - ${NASCOMPOSE_DATA?}/torrents/:/data/
    configs:
      - source: qbittorrent_vpn_settings
        target: /config/wireguard/wg0.conf
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.qbittorrent.middlewares: authelia@file

networks:
  torrents:
    name: torrents

  reverse-proxy:
    external: true

configs:
  qbittorrent_vpn_settings:
    file: ${NASCOMPOSE_SERVICES?}/torrents/secrets/wg0.conf

secrets:
  transmission_vpn_creds:
      file: ${NASCOMPOSE_SERVICES?}/torrents/secrets/vpn_creds
