name: Media-Player

services:
  plex:
    hostname: plex
    image: plexinc/pms-docker:plexpass
    environment:
      PLEX_UID: ${NASCOMPOSE_UID?}
      PLEX_GID: ${NASCOMPOSE_GID?}
    networks:
      - reverse-proxy
      - media-player
    volumes:
      - plex_transcode:/transcode/
      - plex_config:/config/
      - tv:/data/tv/
      - movies:/data/movies/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.services.plex.loadbalancer.server.port: 32400
      traefik.http.services.plex.loadbalancer.server.scheme: https

  audiobookshelf:
    profiles: [ebooks]
    hostname: audiobookshelf
    image: advplyr/audiobookshelf
    environment:
      AUDIOBOOKSHELF_UID: ${NASCOMPOSE_UID?}
      AUDIOBOOKSHELF_GID: ${NASCOMPOSE_GID?}
    networks:
      - reverse-proxy
    volumes:
      - audiobookshelf_config:/config/
      - audiobookshelf_metadata:/metadata/
      - audiobooks:/audiobooks/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.audiobookshelf.middlewares: authelia@file

networks:
  media-player:
    name: media-player

  reverse-proxy:
    external: true

volumes:
  movies:
    name: movies
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_DATA?}/media/movies/
  tv:
    name: tv
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_DATA?}/media/tv/
  audiobooks:
    name: audiobooks
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_DATA?}/media/audiobooks/

  plex_transcode:
  plex_config:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/media-player/volumes/plex_config/
  audiobookshelf_config:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/media-player/volumes/audiobookshelf_config/
  audiobookshelf_metadata:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/media-player/volumes/audiobookshelf_metadata/
