name: media-player

services:
  plex:
    hostname: plex
    image: plexinc/pms-docker:plexpass
    environment:
      PLEX_UID: ${NASCOMPOSE_UID?}
      PLEX_GID: ${NASCOMPOSE_GID?}
    networks:
      - reverse-proxy
      - media-player
      - scrobbler
    volumes:
      - plex_transcode:/transcode/
      - ${NASCOMPOSE_SERVICES?}/media-player/volumes/plex_config/:/config/
      - ${NASCOMPOSE_DATA?}/media/anime/:/data/anime/:ro
      - ${NASCOMPOSE_DATA?}/media/tv/:/data/tv/:ro
      - ${NASCOMPOSE_DATA?}/media/movies/:/data/movies/:ro
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.services.plex.loadbalancer.server.port: 32400
      traefik.http.services.plex.loadbalancer.server.scheme: https

  tautulli:
    hostname: tautulli
    image: lscr.io/linuxserver/tautulli
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - reverse-proxy
      - media-player
    volumes:
      - ${NASCOMPOSE_SERVICES?}/media-player/volumes/tautulli_config/:/config/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.tautulli.middlewares: authelia@file

  audiobookshelf:
    hostname: audiobookshelf
    image: advplyr/audiobookshelf
    profiles: [ebooks]
    environment:
      AUDIOBOOKSHELF_UID: ${NASCOMPOSE_UID?}
      AUDIOBOOKSHELF_GID: ${NASCOMPOSE_GID?}
    networks:
      - reverse-proxy
    volumes:
      - ${NASCOMPOSE_SERVICES?}/media-player/volumes/audiobookshelf_config/:/config/
      - ${NASCOMPOSE_SERVICES?}/media-player/volumes/audiobookshelf_metadata/:/metadata/
      - ${NASCOMPOSE_DATA?}/media/audiobooks/:/audiobooks/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.audiobookshelf.middlewares: authelia@file

networks:
  media-player:
    name: media-player

  reverse-proxy:
    external: true
  scrobbler:
    external: true

volumes:
  plex_transcode:
