name: authentication

services:
  authelia:
    image: authelia/authelia
    command: --config /etc/authelia/configuration.yml,/etc/authelia/access.yml,/etc/authelia/authentication.yml
    environment:
      NASCOMPOSE_TRAEFIK_DOMAINS: ${NASCOMPOSE_TRAEFIK_DOMAINS?}
      AUTHELIA_DEFAULT_REDIRECTION_URL: "" #Heimdall
      AUTHELIA_JWT_SECRET_FILE: /run/secrets/jwt_secret
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/storage_key
    networks:
      - traefik
    volumes:
      - config:/config
    configs:
      - source: authelia_configuration
        target: /etc/authelia/configuration.yml
      - source: authelia_access
        target: /etc/authelia/access.yml
      - source: authelia_authentication
        target: /etc/authelia/authentication.yml
    secrets:
      - jwt_secret
      - storage_key
    labels:
      traefik.enable: true

networks:
  traefik:
    external: true

volumes:
  config:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/authelia/config/

configs:
  authelia_configuration:
    file: ${NASCOMPOSE_SERVICES?}/configs/authelia/configuration.yml
  authelia_access:
    file: ${NASCOMPOSE_SERVICES?}/configs/authelia/access.yml
  authelia_authentication:
    file: ${NASCOMPOSE_SERVICES?}/configs/authelia/authentication.yml

secrets:
  jwt_secret:
    file: ${NASCOMPOSE_SERVICES?}/secrets/authelia/jwt_secret
  storage_key:
    file: ${NASCOMPOSE_SERVICES?}/secrets/authelia/storage_key
