name: authentication

services:
  authelia:
    image: authelia/authelia
    environment:
      NASCOMPOSE_TRAEFIK_DOMAINS: ${NASCOMPOSE_TRAEFIK_DOMAINS?}
      AUTHELIA_DEFAULT_REDIRECTION_URL: "" #Heimdall
      AUTHELIA_JWT_SECRET_FILE: /run/secret/jwt_secret
    networks:
      - traefik
    volumes:
      - config:/config
    secrets:
      - jwt_secret
    labels:
      traefik.enable: true

networks:
  traefik:
    external: true

volumes:
  config:

secrets:
  jwt_secret:
    file: ${NASCOMPOSE_SERVICES?}/secrets/authelia/jwt_secret
