name: Collectors

services:
  mylar:
    image: linuxserver/mylar3
    profiles: [ebooks]
    networks:
      - traefik
      - gotify
      - downloads
    volumes:
      - mylar_config:/config/
      - comics:/comics
      - torrents_completed:/downloads/torrents
      - usenet_completed:/downloads/usenet
    restart: unless-stopped
    labels:
      traefik.enable: true

  lazylibrarian:
    image: linuxserver/lazylibrarian
    profiles: [ebooks]
    networks:
      - traefik
      - gotify
      - downloads
    volumes:
      - lazylibrarian_config:/config/
      - books:/books/
      - torrents_completed:/downloads/torrents/
      - usenet_completed:/downloads/usenet/
    restart: unless-stopped
    labels:
      traefik.enable: true

  sonarr:
    image: linuxserver/sonarr
    networks:
      - traefik
      - gotify
      - downloads
    volumes:
      - sonarr_config:/config/
      - tv:/tv/
      - torrents_completed:/downloads/torrents/
      - usenet_completed:/downloads/usenet/
    restart: unless-stopped
    labels:
      traefik.enable: true

  radarr:
    image: linuxserver/radarr
    networks:
      - traefik
      - gotify
      - downloads
    volumes:
      - radarr_config:/config/
      - movies:/movies/
      - torrents_completed:/downloads/torrents/
      - usenet_completed:/downloads/usenet/
    restart: unless-stopped
    labels:
      traefik.enable: true

  bazarr:
    image: linuxserver/bazarr
    networks:
      - traefik
      - gotify
    volumes:
      - bazarr_config:/config/
      - movies:/movies/
      - tv:/tv/
    restart: unless-stopped
    labels:
      traefik.enable: true

networks:
  traefik:
    external: true
  gotify:
    external: true
  downloads:
    external: true

volumes:
  books:
    external: true
  comics:
    external: true
  movies:
    external: true
  tv:
    external: true

  torrents_completed:
    external: true
  usenet_completed:
    external: true

  mylar_config:
    driver_opts:
      type: none
      o: bind
      device: ${SERVICES_DIR?}/mylar/volumes/config/
  lazylibrarian_config:
    driver_opts:
      type: none
      o: bind
      device: ${SERVICES_DIR?}/lazylibrarian/volumes/config/
  sonarr_config:
    driver_opts:
      type: none
      o: bind
      device: ${SERVICES_DIR?}/sonarr/volumes/config/
  radarr_config:
    driver_opts:
      type: none
      o: bind
      device: ${SERVICES_DIR?}/radarr/volumes/config/
  bazarr_config:
    driver_opts:
      type: none
      o: bind
      device: ${SERVICES_DIR?}/bazarr/volumes/config/
