name: Collectors

services:
  mylar:
    image: linuxserver/mylar3
    networks:
      - traefik
    volumes:
      - mylar_config:/config/
      - comics:/comics
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.mylar.rule: HostRegexp(`mylar{subdomain:(\.[a-z0-9-]+)?}.dedicated.contact`)

  lazylibrarian:
    image: linuxserver/lazylibrarian
    networks:
      - traefik
    volumes:
      - lazylibrarian_config:/config/
      - books:/books
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.lazylibrarian.rule: HostRegexp(`lazylibrarian{subdomain:(\.[a-z0-9-]+)?}.dedicated.contact`)

  sonarr:
    image: linuxserver/sonarr
    networks:
      - traefik
    volumes:
      - sonarr_config:/config/
      - tv:/tv
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.rule: HostRegexp(`sonarr{subdomain:(\.[a-z0-9-]+)?}.dedicated.contact`)

  radarr:
    image: linuxserver/radarr
    networks:
      - traefik
    volumes:
      - radarr_config:/config/
      - movies:/movies
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.rule: HostRegexp(`radarr{subdomain:(\.[a-z0-9-]+)?}.dedicated.contact`)

  bazarr:
    image: linuxserver/bazarr
    networks:
      - traefik
    volumes:
      - bazarr_config:/config/
      - movies:/movies
      - tv:/tv
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.bazarr.rule: HostRegexp(`bazarr{subdomain:(\.[a-z0-9-]+)?}.dedicated.contact`)


networks:
  gotify:
    external: true
  traefik:
    external: true

volumes:
  books:
    external: true
  comics:
    external: true
  movies:
    external: true
  tv:
    external: true

  mylar_config:
    driver_opts:
      type: none
      o: bind
      device: ${SERVICES_DIR?}/mylar/volumes/config/
  lazylibrarian_config:
    driver_opts:
      type: none
      o: bind
      device: ${SERVICES_DIR?}/lazylibrarian/volumes/config/
  sonarr_config:
    driver_opts:
      type: none
      o: bind
      device: ${SERVICES_DIR?}/sonarr/volumes/config/
  radarr_config:
    driver_opts:
      type: none
      o: bind
      device: ${SERVICES_DIR?}/radarr/volumes/config/
  bazarr_config:
    driver_opts:
      type: none
      o: bind
      device: ${SERVICES_DIR?}/bazarr/volumes/config/
