name: Collectors

services:
  mylar:
    image: linuxserver/mylar3
    profiles: [ebooks]
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - traefik
      - downloads
    volumes:
      - mylar_config:/config/
      - data:/data
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.mylar.middlewares: authentik@file

  lazylibrarian:
    image: linuxserver/lazylibrarian
    profiles: [ebooks]
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - traefik
      - downloads
    volumes:
      - lazylibrarian_config:/config/
      - data:/data
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.lazylibrarian.middlewares: authentik@file

  sonarr:
    image: linuxserver/sonarr
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - traefik
      - downloads
    volumes:
      - sonarr_config:/config/
      - data:/data
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.middlewares: authentik@file

  radarr:
    image: linuxserver/radarr
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - traefik
      - downloads
    volumes:
      - radarr_config:/config/
      - data:/data
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.middlewares: authentik@file

  bazarr:
    image: linuxserver/bazarr
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - traefik
    volumes:
      - bazarr_config:/config/
      - data:/data
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.bazarr.middlewares: authentik@file

  ombi:
    image: linuxserver/ombi
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - traefik
      - downloads
    volumes:
      - ombi_config:/config/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.ombi.middlewares: authentik@file

networks:
  traefik:
    external: true
  downloads:
    external: true

volumes:
  data:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_DATA?}

  mylar_config:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/mylar/config/
  lazylibrarian_config:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/lazylibrarian/config/
  sonarr_config:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/sonarr/config/
  radarr_config:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/radarr/config/
  bazarr_config:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/bazarr/config/
  ombi_config:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/ombi/config/
