name: Downloads

services:
  nzbget:
    image: linuxserver/nzbget
    profiles: [usenet]
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - traefik
      - downloads
    volumes:
      - nzbget_config:/config
      - usenet:/downloads
    restart: unless-stopped
    labels:
      traefik.enable: true

networks:
  downloads:
    name: downloads

  traefik:
    external: true

volumes:
  usenet:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_DATA?}/usenet/

  nzbget_config:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/nzbget/config/
