name: Downloads

services:
  dummy:
    image: alpine
    entrypoint: sleep infinity
    volumes:
      - torrents:/torrents/
      - torrents_completed:/torrents/completed
      - usenet:/usenet/
      - usenet_completed:/usenet/completed
  prowlarr:
    image: linuxserver/prowlarr:develop #TODO: Move to a stable version!
    networks:
      - default
      - traefik
      - gotify
      - downloads
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - prowlarr_config:/config/
    restart: unless-stopped
    labels:
      traefik.enable: true
  flaresolverr:
    image: ngosang/flaresolverr:3.0.0.beta3 #TODO: Move to a stable version!
    restart: unless-stopped
# TODO:
# NZBGet
# Transmission

networks:
  downloads:
    name: downloads

  traefik:
    external: true
  gotify:
    external: true

volumes:
  torrents_completed:
    name: torrents_completed
    driver_opts:
      type: none
      o: bind
      device: ${DOWNLOADS_DIR?}/torrents/completed
  usenet_completed:
    name: usenet_completed
    driver_opts:
      type: none
      o: bind
      device: ${DOWNLOADS_DIR?}/usenet/completed

  torrents:
    driver_opts:
      type: none
      o: bind
      device: ${DOWNLOADS_DIR?}/torrents
  usenet:
    driver_opts:
      type: none
      o: bind
      device: ${DOWNLOADS_DIR?}/usenet

  prowlarr_config:
    driver_opts:
      type: none
      o: bind
      device: ${SERVICES_DIR?}/prowlarr/volumes/config/
