name: Downloads

services:
  prowlarr:
    image: linuxserver/prowlarr
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - default
      - traefik
      - downloads
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - prowlarr_config:/config/
    restart: unless-stopped
    labels:
      traefik.enable: true

  flaresolverr:
    image: flaresolverr/flaresolverr
    restart: unless-stopped

  transmission:
    image: haugene/transmission-openvpn
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
      OPENVPN_PROVIDER: PIA
      OPENVPN_CONFIG: ${NASCOMPOSE_TRANSMISSION_VPNREGION?}
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
      LOCAL_NETWORK: 192.168.0.0/16
      TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: true
    cap_add:
      - NET_ADMIN
    networks:
      - traefik
      - downloads
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - transmission_config:/config/
      - torrents:/data/
    configs:
      - source: transmission_openvpn_post_config
        target: /scripts/openvpn-post-config.sh
    secrets:
      - source: transmission_rpc_creds
        target: rpc_creds
      - source: transmission_vpn_creds
        target: openvpn_creds
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.services.transmission.loadbalancer.server.port: 9091

  youtube-dl:
    image: alexta69/metube
    environment:
      UID: ${NASCOMPOSE_UID?}
      GID: ${NASCOMPOSE_GID?}
      YTDL_OPTIONS: >
        {
          "writesubtitles": true,
          "subtitleslangs": ["all", "-live_chat"],
          "subtitlesformat": "ass/srt/best",
          "postprocessors": [
            { "key": "FFmpegEmbedSubtitle" }
          ]
        }
    networks:
      - traefik
    volumes:
      - youtube:/downloads
    restart: unless-stopped
    labels:
      traefik.enable: true

  nzbget:
    image: linuxserver/nzbget
    profiles: [usenet]
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - traefik
      - downloads
    volumes:
      - nzbget_config:/config
      - usenet:/downloads
    restart: unless-stopped
    labels:
      traefik.enable: true

networks:
  downloads:
    name: downloads

  traefik:
    external: true

volumes:
  torrents:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_DATA?}/torrents/
  usenet:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_DATA?}/usenet/
  youtube:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_DATA?}/youtube/

  prowlarr_config:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/prowlarr/config/
  transmission_config:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/transmission/config/
  transmission_scripts:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/transmission/scripts/
  nzbget_config:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/nzbget/config/

configs:
  transmission_openvpn_post_config:
    file: ${NASCOMPOSE_SERVICES?}/configs/transmission/openvpn-post-config.sh

secrets:
    transmission_rpc_creds:
        file: ${NASCOMPOSE_SERVICES?}/secrets/transmission/rpc_creds
    transmission_vpn_creds:
        file: ${NASCOMPOSE_SERVICES?}/secrets/transmission/vpn_creds
