name: Downloads

services:
  dummy:
    image: alpine
    entrypoint: sleep infinity
    volumes:
      - torrents:/torrents
      - torrents_completed:/torrents/completed
      - usenet:/usenet
      - usenet_completed:/usenet/completed
  prowlarr:
    image: linuxserver/prowlarr:develop #TODO: Move to a stable version!
    networks:
      - traefik
      - gotify
      - downloads
    volumes:
      - prowlarr:/config
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.rule: HostRegexp(`prowlarr{subdomain:(\.[a-z0-9-]+)?}.dedicated.contact`)
# TODO:
# NZBGet
# Transmission

networks:
  downloads:
    name: downloads

  traefik:
    external: true
  gotify:
    external: true

volumes:
  torrents_completed:
    name: torrents_completed
    driver_opts:
      type: none
      o: bind
      device: ${DOWNLOADS_DIR?}/torrents/completed
  usenet_completed:
    name: usenet_completed
    driver_opts:
      type: none
      o: bind
      device: ${DOWNLOADS_DIR?}/usenet/completed

  torrents:
    driver_opts:
      type: none
      o: bind
      device: ${DOWNLOADS_DIR?}/torrents
  usenet:
    driver_opts:
      type: none
      o: bind
      device: ${DOWNLOADS_DIR?}/usenet