name: Downloads

services:
  prowlarr:
    image: linuxserver/prowlarr
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - default
      - traefik
      - downloads
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - prowlarr_config:/config/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.middlewares: authelia@file

  flaresolverr:
    image: flaresolverr/flaresolverr
    restart: unless-stopped

  transmission:
    image: haugene/transmission-openvpn
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
      OPENVPN_PROVIDER: PIA
      OPENVPN_CONFIG: ${NASCOMPOSE_TRANSMISSION_VPNREGION?}
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
      LOCAL_NETWORK: 192.168.0.0/16
    cap_add:
      - NET_ADMIN
    networks:
      - traefik
      - downloads
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - transmission_config:/config/
      - torrents:/data/
    secrets:
      - source: transmission_vpn_creds
        target: openvpn_creds
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.services.transmission.loadbalancer.server.port: 9091
      traefik.http.routers.transmission.middlewares: authelia@file

  youtube-dl:
    image: alexta69/metube
    environment:
      UID: ${NASCOMPOSE_UID?}
      GID: ${NASCOMPOSE_GID?}
      YTDL_OPTIONS: >
        {
          "writesubtitles": true,
          "subtitleslangs": ["all", "-live_chat"],
          "subtitlesformat": "ass/srt/best",
          "postprocessors": [
            { "key": "FFmpegEmbedSubtitle" },
            { "key": "FFmpegMetadata" }
          ]
        }
    networks:
      - traefik
    volumes:
      - youtube:/downloads
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.youtube-dl.middlewares: authelia@file

  nzbget:
    image: linuxserver/nzbget
    profiles: [usenet]
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - traefik
      - downloads
    volumes:
      - nzbget_config:/config
      - usenet:/downloads
    restart: unless-stopped
    labels:
      traefik.enable: true

networks:
  downloads:
    name: downloads

  traefik:
    external: true

volumes:
  torrents:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_DATA?}/torrents/
  usenet:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_DATA?}/usenet/
  youtube:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_DATA?}/youtube/

  prowlarr_config:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/prowlarr/config/
  transmission_config:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/transmission/config/
  nzbget_config:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/nzbget/config/

secrets:
    transmission_vpn_creds:
        file: ${NASCOMPOSE_SERVICES?}/secrets/transmission/vpn_creds
