name: Collectors

services:
  dummy:
    image: alpine
    entrypoint: sleep infinity
    volumes:
      - books:/books/
      - comics:/comics/

  plex:
    image: plexinc/pms-docker:plexpass
    ports:
      - 32400:32400 #TODO Use MacVLAN instead
    networks:
      - default
      - traefik
      - macvlan
    volumes:
      - plex_data:/data
      - tv:/tv
      - movies:/movies
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.services.plex.loadbalancer.server.port: 32400 #TODO: Check if needed
      traefik.http.services.plex.loadbalancer.server.scheme: https #TODO: Check if needed

  plaxt:
    image: xanderstrike/goplaxt
    profiles: [plaxt]
    environment:
      TRAKT_ID: '' #TODO Define properly
      TRAKT_SECRET: '' #TODO Define properly
    networks:
      - default
      - traefik
    volumes:
      - plaxt_keystore:/app/keystore
    restart: unless-stopped
    labels:
      traefik.enable: true

  # TODO:
  # Calibre-web
  # Komga/Kavita

networks:
  traefik:
    external: true
  macvlan:
    external: true

volumes:
  books:
    name: books
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_MEDIA?}/books/
  comics:
    name: comics
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_MEDIA?}/comics/
  movies:
    name: movies
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_MEDIA?}/movies/
  tv:
    name: tv
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_MEDIA?}/tv/
  recycle_bin:
    name: recycle_bin
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_MEDIA?}/recycle_bin/

  plex_data:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/plex/volumes/data/
  plaxt_keystore:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/plaxt/volumes/keystore/
