name: Collectors

services:
  dummy:
    image: alpine
    entrypoint: sleep infinity
    volumes:
      - books:/books/
      - comics:/comics/

  plex:
    image: plexinc/pms-docker:plexpass
    environment:
      PLEX_UID: ${NASCOMPOSE_UID?}
      PLEX_GID: ${NASCOMPOSE_GID?}
      PLEX_CLAIM: ${NASCOMPOSE_PLEX_CLAIM}
    ports:
      - 32400:32400
    networks:
      - macvlan
      - default
      - traefik
    volumes:
      - /tmp/plex/:/transcode/ # Mount in tmpfs
      - plex_config:/config/
      - tv:/data/tv/
      - movies:/data/movies/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.services.plex.loadbalancer.server.port: 32400 #TODO: Check if needed
      traefik.http.services.plex.loadbalancer.server.scheme: https #TODO: Check if needed

  plaxt:
    image: xanderstrike/goplaxt
    profiles: [plaxt]
    user: ${NASCOMPOSE_UID?}:${NASCOMPOSE_GID?}
    environment:
      TRAKT_ID: '' #TODO Define properly
      TRAKT_SECRET: '' #TODO Define properly
    networks:
      - default
      - traefik
    volumes:
      - plaxt_keystore:/app/keystore/
    restart: unless-stopped
    labels:
      traefik.enable: true

  # TODO:
  # Calibre-web
  # Komga/Kavita

networks:
  macvlan:
    external: true
  traefik:
    external: true

volumes:
  books:
    name: books
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_DATA?}/media/books/
  comics:
    name: comics
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_DATA?}/media/comics/
  movies:
    name: movies
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_DATA?}/media/movies/
  tv:
    name: tv
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_DATA?}/media/tv/
  # TODO: Manage recycle bin properly...
  recycle_bin:
    name: recycle_bin
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_DATA?}/media/recycle_bin/

  plex_config:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/plex/config/
  plaxt_keystore:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/plaxt/keystore/
