name: Collectors

services:
  plex:
    image: plexinc/pms-docker:plexpass
    environment:
      PLEX_UID: ${NASCOMPOSE_UID?}
      PLEX_GID: ${NASCOMPOSE_GID?}
    ports:
      - 32400:32400
    networks:
      - macvlan
      - default
      - traefik
    volumes:
      - plex_transcode:/transcode/
      - plex_config:/config/
      - tv:/data/tv/
      - movies:/data/movies/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.services.plex.loadbalancer.server.port: 32400
      traefik.http.services.plex.loadbalancer.server.scheme: https

  plaxt:
    image: xanderstrike/goplaxt
    profiles: [plaxt]
    user: ${NASCOMPOSE_UID?}:${NASCOMPOSE_GID?}
    environment:
      TRAKT_ID_FILE: /run/secrets/trakt_id
      TRAKT_SECRET_FILE: /run/secrets/trakt_secret
    networks:
      - default
      - traefik
    volumes:
      - plaxt_keystore:/app/keystore/
    secrets:
      - trakt_id
      - trakt_secret
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.smokeping.middlewares: authelia@file

  # TODO:
  # Calibre-web
  # Komga/Kavita

networks:
  macvlan:
    external: true
  traefik:
    external: true

volumes:
  books:
    name: books
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_DATA?}/media/books/
  comics:
    name: comics
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_DATA?}/media/comics/
  movies:
    name: movies
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_DATA?}/media/movies/
  tv:
    name: tv
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_DATA?}/media/tv/
  # TODO: Manage recycle bin properly...
  recycle_bin:
    name: recycle_bin
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_DATA?}/media/recycle_bin/

  plex_transcode:
  plex_config:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/plex/config/
  plaxt_keystore:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/plaxt/keystore/

secrets:
  trakt_id:
    file: ${NASCOMPOSE_SERVICES?}/secrets/plaxt/trakt_id
  trakt_secret:
    file: ${NASCOMPOSE_SERVICES?}/secrets/plaxt/trakt_secret
