services:
  diun:
    image: crazymax/diun
    networks:
      - docker
      - gotify
    volumes:
      - diun:/data
    configs:
      - source: diun
        target: /etc/diun/
    secrets:
      - gotify_token
    restart: unless-stopped

  smokeping:
    image: linuxserver/smokeping
    networks:
      - traefik
    volumes:
      - smokeping:/data
#    configs:
#      - source: smokeping
#        target: /config/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.smokeping.rule: HostRegexp(`smokeping{subdomain:(\.[a-z0-9-]+)?}.dedicated.contact`)

networks:
  docker:
    external: true
  gotify:
    external: true
  traefik:
    external: true

volumes:
  diun:
    driver_opts:
      type: none
      o: bind
      device: ${MOUNT_DIR?}/diun/data/
  smokeping:
    driver_opts:
      type: none
      o: bind
      device: ${MOUNT_DIR?}/smokeping/data/

configs:
  diun:
    file: ${MOUNT_DIR?}/diun/config/
#  smokeping:
#    file: ${MOUNT_DIR?}/smokeping/config/

secrets:
  gotify_token:
    file: ${MOUNT_DIR?}/diun/secrets/gotify_token
