services:
  watchtower:
    image: containrrr/watchtower
    environment:
      DOCKER_HOST: tcp://docker:2375
      WATCHTOWER_INCLUDE_RESTARTING: true
      WATCHTOWER_INCLUDE_STOPPED: true
      WATCHTOWER_MONITOR_ONLY: true
      WATCHTOWER_NOTIFICATIONS: gotify
      WATCHTOWER_NOTIFICATION_GOTIFY_URL: http://gotify
      WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN: /run/secrets/gotify_token
    networks:
      - docker
      - gotify
    secrets:
      - source: watchtower_gotify_token
        target: gotify_token
    restart: unless-stopped

  smokeping:
    image: linuxserver/smokeping
    networks:
      - traefik
    volumes:
      - smokeping_data:/data/
      - smokeping_config:/config/
    restart: unless-stopped
    labels:
      traefik.enable: true

  duckdns:
    image: linuxserver/duckdns
    environment:
      - SUBDOMAINS=${DUCK_DNS_DOMAIN?}
      - FILE__TOKEN=/run/secrets/duckdns_token
    secrets:
      - duckdns_token
    restart: unless-stopped

networks:
  docker:
    external: true
  gotify:
    external: true
  traefik:
    external: true

volumes:
  smokeping_data:
    driver_opts:
      type: none
      o: bind
      device: ${SERVICES_DIR?}/smokeping/volumes/data/
  smokeping_config:
    driver_opts:
      type: none
      o: bind
      device: ${SERVICES_DIR?}/smokeping/volumes/config/
  ddclient_data:
    driver_opts:
      type: none
      o: bind
      device: ${SERVICES_DIR?}/ddclient/volumes/data/
  ddclient_config:
    driver_opts:
      type: none
      o: bind
      device: ${SERVICES_DIR?}/ddclient/volumes/config/
  ddclient_init:
    driver_opts:
      type: none
      o: bind
      device: ${SERVICES_DIR?}/ddclient/volumes/init/

configs:
  ddclient_config_tpl:
    file: ${SERVICES_DIR?}/ddclient/configs/ddclient.conf.tpl

secrets:
  watchtower_gotify_token:
    file: ${SERVICES_DIR?}/watchtower/secrets/gotify_token
  duckdns_token:
    file: ${SERVICES_DIR?}/ddclient/secrets/duckdns_token
