services:
  watchtower:
    image: containrrr/watchtower
    environment:
      DOCKER_HOST: tcp://docker:2375
      WATCHTOWER_INCLUDE_RESTARTING: true
      WATCHTOWER_INCLUDE_STOPPED: true
      WATCHTOWER_MONITOR_ONLY: true
      WATCHTOWER_NOTIFICATIONS: gotify
      WATCHTOWER_NOTIFICATION_GOTIFY_URL: http://gotify
      WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN: /run/secrets/gotify_token
    networks:
      - docker
      - gotify
    secrets:
      - source: watchtower_gotify_token
        target: gotify_token
    restart: unless-stopped

  smokeping:
    image: linuxserver/smokeping
    networks:
      - traefik
    volumes:
      - smokeping_data:/data/
      - smokeping_config:/config/
    restart: unless-stopped
    labels:
      traefik.enable: true

  duckdns:
    image: linuxserver/duckdns
    environment:
      - SUBDOMAINS=${NASCOMPOSE_DUCKDNS_DOMAIN?}
      - FILE__TOKEN=/run/secrets/duckdns_token
    secrets:
      - duckdns_token
    restart: unless-stopped

  heimdall:
    image: linuxserver/heimdall
    networks:
      - traefik
    volumes:
      - heimdall_config:/config/
    restart: unless-stopped
    labels:
      traefik.enable: true

  # TODO: Set up synology/external services?

networks:
  docker:
    external: true
  gotify:
    external: true
  traefik:
    external: true

volumes:
  smokeping_data:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/smokeping/data/
  smokeping_config:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/smokeping/config/
  heimdall_config:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/heimdall/config/

secrets:
  watchtower_gotify_token:
    file: ${NASCOMPOSE_SERVICES?}/secrets/watchtower/gotify_token
  duckdns_token:
    file: ${NASCOMPOSE_SERVICES?}/secrets/duckdns/duckdns_token
