services:
  watchtower:
    image: containrrr/watchtower
    environment:
      DOCKER_HOST: tcp://docker:2375
      WATCHTOWER_INCLUDE_RESTARTING: true
      WATCHTOWER_INCLUDE_STOPPED: true
      WATCHTOWER_MONITOR_ONLY: true
      WATCHTOWER_NOTIFICATION_URL: /run/secrets/watchtower_notification_url
    networks:
      - docker
    secrets:
      - watchtower_notification_url
    restart: unless-stopped

  smokeping:
    image: linuxserver/smokeping
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - traefik
    volumes:
      - smokeping_data:/data/
      - smokeping_config:/config/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.smokeping.middlewares: authelia@file

networks:
  docker:
    external: true
  traefik:
    external: true

volumes:
  smokeping_data:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/smokeping/data/
  smokeping_config:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/smokeping/config/

secrets:
  watchtower_notification_url:
    file: ${NASCOMPOSE_SERVICES?}/secrets/watchtower/notification_url
