name: SSH Protection

services:
  endlessh:
    hostname: endlessh
    image: linuxserver/endlessh
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - reverse-proxy
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.tcp.routers.endlessh.entryPoints: ssh
      traefik.tcp.routers.endlessh.service: endlessh
      traefik.tcp.services.endlessh.loadbalancer.server.port: 2222

networks:
  reverse-proxy:
    external: true
