name: Scrobbler

services:
  # Always create the usenet network even if the usenet profile is disabled
  dummy:
    image: tianon/true
    networks:
      - scrobbler

  plaxt:
    hostname: plaxt
    image: xanderstrike/goplaxt
    profiles: [plaxt]
    user: ${NASCOMPOSE_UID?}:${NASCOMPOSE_GID?}
    environment:
      TRAKT_ID_FILE: /run/secrets/trakt_id
      TRAKT_SECRET_FILE: /run/secrets/trakt_secret
    networks:
      - reverse-proxy
      - scrobbler
    volumes:
      - ${NASCOMPOSE_SERVICES?}/scrobbler/volumes/plaxt_keystore/:/app/keystore/
      # Secrets
      - ${NASCOMPOSE_SERVICES?}/scrobbler/secrets/trakt_id:/run/secrets/trakt_id:ro
      - ${NASCOMPOSE_SERVICES?}/scrobbler/secrets/trakt_secret:/run/secrets/trakt_secret:ro
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.plaxt.middlewares: authelia@file

networks:
  scrobbler:
    name: scrobbler

  reverse-proxy:
    external: true
