name: notifiarr

services:
  notifiarr:
    hostname: notifiarr
    image: golift/notifiarr
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
      DN_MODE: ${NASCOMPOSE_NOTIFIARR_MODE?}
    networks:
      - reverse-proxy
    volumes:
      - ${NASCOMPOSE_SERVICES?}/notifiarr/volumes/notifiarr_config/:/config/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.notifiarr.middlewares: authelia@file

networks:
  reverse-proxy:
    external: true
