name: docker-monitoring

services:
  watchtower:
    hostname: watchtower
    image: containrrr/watchtower
    environment:
      DOCKER_HOST: tcp://docker:2375
      WATCHTOWER_INCLUDE_RESTARTING: true
      WATCHTOWER_INCLUDE_STOPPED: true
      WATCHTOWER_NOTIFICATION_REPORT: true
      WATCHTOWER_NOTIFICATION_URL: /run/secrets/watchtower_notification_url
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Secrets
      - ${NASCOMPOSE_SERVICES?}/docker-monitoring/secrets/notification_url:/run/secrets/watchtower_notification_url:ro
    restart: unless-stopped
