http:
  routers:
    traefik:
      rule: Host(`traefik`) || Host(`traefik.{{ env `NASCOMPOSE_TRAEFIK_DOMAIN` }}`)
      service: api@internal
      middlewares:
        - traefik-auth
  middlewares:
    traefik-auth:
      basicAuth:
        usersFile: /run/secrets/traefik_password
