name: Comic collector

services:
  mylar:
    hostname: mylar
    image: lscr.io/linuxserver/mylar3
    profiles: [ebooks]
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - reverse-proxy
      - torrents
      - usenet
    volumes:
      - ${NASCOMPOSE_SERVICES?}/comic-collector/volumes/mylar_config/:/config/
      - ${NASCOMPOSE_DATA?}/:/data/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.mylar.middlewares: authelia@file

networks:
  reverse-proxy:
    external: true
  torrents:
    external: true
  usenet:
    external: true
