services:
  traefik:
    environment:
      NASCOMPOSE_MACVLAN_SYNOLOGY_IP: ${NASCOMPOSE_MACVLAN_HOST_IP?}
      NASCOMPOSE_MACVLAN_PORTAINER_IP: ${NASCOMPOSE_MACVLAN_PORTAINER_IP?}
    networks:
      macvlan:
        ipv4_address: ${NASCOMPOSE_MACVLAN_TRAEFIK_IP?}

networks:
  macvlan:
    external: true
