providers:
  docker:
    endpoint: tcp://docker:2375
    exposedByDefault: false
    network: traefik

api:
  insecure: true

accessLog: {}

entryPoints:
  web:
    address: :80
    http:
#      redirections:
#        entryPoint:
#          to: websecure
#          scheme: https
  websecure:
    address: :443
    http:
      tls: {}
