name: Media requester

services:
  ombi:
    hostname: ombi
    image: lscr.io/linuxserver/ombi
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - reverse-proxy
      - media-player
      - tv-collector
      - movie-collector
    volumes:
      - ${NASCOMPOSE_SERVICES?}/media-requester/volumes/ombi_config/:/config/
    restart: unless-stopped
    labels:
      traefik.enable: true

networks:
  reverse-proxy:
    external: true
  tv-collector:
    external: true
  movie-collector:
    external: true
  media-player:
    external: true
