name: usenet

services:
  # Always create the usenet network even if the usenet profile is disabled
  dummy:
    image: tianon/true
    networks:
      - usenet

  sabnzbd:
    hostname: sabnzbd
    image: lscr.io/linuxserver/sabnzbd
    profiles: [usenet]
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - reverse-proxy
      - usenet
    volumes:
      - ${NASCOMPOSE_SERVICES?}/usenet/volumes/sabnzbd_config/:/config/
      - ${NASCOMPOSE_DATA?}/usenet/:/data/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.sabnzbd.middlewares: authelia@file

networks:
  usenet:
    name: usenet

  reverse-proxy:
    external: true
