name: indexer

services:
  prowlarr:
    hostname: prowlarr
    image: lscr.io/linuxserver/prowlarr
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - reverse-proxy
      - default
      - indexer
      - torrents
      - usenet
    dns:
      # Work around DNS blocks in various regions
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ${NASCOMPOSE_SERVICES?}/indexer/volumes/prowlarr_config/:/config/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.middlewares: authelia@file

  flaresolverr:
    hostname: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:pr-1282 # Temporary until https://github.com/FlareSolverr/FlareSolverr/pull/1272 gets fixed
    restart: unless-stopped
    dns:
      # Work around DNS blocks in various regions
      - 1.1.1.1
      - 1.0.0.1

  autobrr:
    hostname: autobrr
    image: ghcr.io/autobrr/autobrr
    user: ${NASCOMPOSE_UID?}:${NASCOMPOSE_GID?}
    networks:
      - reverse-proxy
      - default
      - torrents
    dns:
      # Work around DNS blocks in various regions
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ${NASCOMPOSE_SERVICES?}/indexer/volumes/autobrr_config/:/config/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.autobrr.middlewares: authelia@file

  omegabrr:
    hostname: omegabrr
    image: ghcr.io/autobrr/omegabrr
    user: ${NASCOMPOSE_UID?}:${NASCOMPOSE_GID?}
    networks:
      - reverse-proxy
      - default
    volumes:
      - ${NASCOMPOSE_SERVICES?}/indexer/volumes/omegabrr_config/:/config/
    restart: unless-stopped

networks:
  indexer:
    name: indexer

  reverse-proxy:
    external: true
  torrents:
    external: true
  usenet:
    external: true
