name: eBook-Reader

services:
  calibre:
    hostname: calibre
    image: linuxserver/calibre
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - reverse-proxy
      - calibre
    volumes:
      - ${NASCOMPOSE_SERVICES?}/ebook-reader/volumes/calibre_config/:/config/
      - ${NASCOMPOSE_DATA?}/media/ebooks/:/ebooks/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.services.calibre.loadbalancer.server.port: 8080

  calibre-web:
    hostname: calibre-web
    image: linuxserver/calibre-web
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - reverse-proxy
      - calibre
    volumes:
      - ${NASCOMPOSE_SERVICES?}/ebook-reader/volumes/calibre-web_config/:/config/
      - ${NASCOMPOSE_DATA?}/media/ebooks/:/ebooks/
    restart: unless-stopped
    labels:
      traefik.enable: true

networks:
  calibre:
    name: calibre

  reverse-proxy:
    external: true
