name: Dynamic DNS

services:
  duckdns:
    hostname: duckdns
    image: linuxserver/duckdns
    environment:
      - SUBDOMAINS=${NASCOMPOSE_DUCKDNS_DOMAIN?}
      - FILE__TOKEN=/run/secrets/duckdns_token
    volumes:
      # Secrets
      - ${NASCOMPOSE_SERVICES?}/dynamic-dns/secrets/duckdns_token:/run/secrets/duckdns_token:ro
    restart: unless-stopped
