providers:
  docker:
    endpoint: tcp://docker:2375
    exposedByDefault: false
    network: traefik
    defaultRule: '{{ $s := index .Labels "com.docker.compose.service" }}{{ range $i, $d := splitList "," (env `NASCOMPOSE_TRAEFIK_DOMAINS`) }}{{ if $i }} || {{end}}Host(`{{ $s }}.{{ $d }}`){{ end }}'
  file:
    directory: /etc/traefik/dynamic/

serverstransport:
  insecureskipverify: true

api: {}
accessLog: {}

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    asDefault: true
    address: :443
    http:
      tls: {}
      middlewares:
        - hsts@file

global:
  sendAnonymousUsage: false
