providers:
  docker:
    endpoint: tcp://docker:2375
    exposedByDefault: false
    network: reverse-proxy
    defaultRule: '{{ $s := index .Labels "com.docker.compose.service" }}{{ range $i, $d := splitList "," (env `NASCOMPOSE_TRAEFIK_DOMAINS`) }}{{ if $i }} || {{end}}Host(`{{ $s }}.{{ $d }}`){{ end }}'
  file:
    directory: /etc/traefik/dynamic/

serverstransport:
  insecureskipverify: true

api: {}
accessLog: {}

certificatesResolvers:
  defaultResolver:
    acme:
      storage: /etc/traefik/acme/acme.json
      dnsChallenge:
        provider: cloudflare

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    http:
      tls:
        certResolver: defaultResolver
      middlewares:
        - hsts@file
  ssh:
    address: :22

global:
  sendAnonymousUsage: false
