http:
  middlewares:
    #TODO: Convert to inline configuration for notifiarr
    notifiarr-authelia:
      plugin:
        htransformation:
          Rules:
            - Type: Rename
              Header: Remote-User
              Value: X-WebAuth-User
