http:
  #TODO: Convert to inline configuration for portainer
  routers:
    portainer:
      rule: 'Host(`portainer.{{ env `NASCOMPOSE_DOMAIN` }}`)'
      service: portainer@file
  services:
    portainer:
      loadBalancer:
        servers:
          - url: https://{{ env `NASCOMPOSE_MACVLAN_PORTAINER_IP` }}:9443/
