http:
  routers:
    synology:
      rule: 'synology.{{ env `NASCOMPOSE_DOMAIN` }}'
      service: synology@file
  services:
    synology:
      loadBalancer:
        servers:
          - url: https://{{ env `NASCOMPOSE_MACVLAN_SYNOLOGY_IP` }}:5001/
