name: Youtube-DL

services:
  youtube-dl:
    hostname: youtube-dl
    image: alexta69/metube
    environment:
      UID: ${NASCOMPOSE_UID?}
      GID: ${NASCOMPOSE_GID?}
      YTDL_OPTIONS: >
        {
          "writesubtitles": true,
          "subtitleslangs": ["all", "-live_chat"],
          "subtitlesformat": "ass/srt/best",
          "postprocessors": [
            { "key": "FFmpegEmbedSubtitle" },
            { "key": "FFmpegMetadata" }
          ]
        }
    networks:
      - reverse-proxy
    volumes:
      - youtube-dl:/downloads
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.youtube-dl.middlewares: authelia@file

networks:
  reverse-proxy:
    external: true

volumes:
  youtube-dl:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_DATA?}/youtube-dl/
