name: youtube-dl

services:
  ytdl:
    hostname: ytdl
    image: alexta69/metube
    environment:
      UID: ${NASCOMPOSE_UID?}
      GID: ${NASCOMPOSE_GID?}
      YTDL_OPTIONS: >
        {
          "writesubtitles": true,
          "subtitleslangs": ["all", "-live_chat"],
          "subtitlesformat": "ass/srt/best",
          "postprocessors": [
            { "key": "FFmpegEmbedSubtitle" },
            { "key": "FFmpegMetadata" }
          ]
        }
    networks:
      - reverse-proxy
    volumes:
      - ${NASCOMPOSE_DATA?}/ytdl/:/downloads/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.ytdl.middlewares: authelia@file

  mkvtoolnix:
    hostname: mkvtoolnix
    image: jlesage/mkvtoolnix
    environment:
      USER_ID: ${NASCOMPOSE_UID?}
      GROUP_ID: ${NASCOMPOSE_GID?}
    networks:
      - reverse-proxy
    volumes:
      - ${NASCOMPOSE_SERVICES?}/youtube-dl/volumes/mkvtoolnix_config/:/config/
      - ${NASCOMPOSE_DATA?}/ytdl/:/storage/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.mkvtoolnix.middlewares: authelia@file

networks:
  reverse-proxy:
    external: true
