name: subtitle-collector

services:
  bazarr:
    hostname: bazarr
    image: lscr.io/linuxserver/bazarr
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - reverse-proxy
      - movie-collector
      - tv-collector
    volumes:
      - ${NASCOMPOSE_SERVICES?}/subtitle-collector/volumes/bazarr_config/:/config/
      - ${NASCOMPOSE_DATA?}/media/movies/:/data/media/movies/
      - ${NASCOMPOSE_DATA?}/media/tv/:/data/media/tv/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.bazarr.middlewares: authelia@file

networks:
  reverse-proxy:
    external: true
  movie-collector:
    external: true
  tv-collector:
    external: true
