name: network-monitoring

services:
  smokeping:
    hostname: smokeping
    image: lscr.io/linuxserver/smokeping
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - reverse-proxy
    volumes:
      - ${NASCOMPOSE_SERVICES?}/network-monitoring/volumes/smokeping_config/:/config/
      - ${NASCOMPOSE_SERVICES?}/network-monitoring/volumes/smokeping_data/:/data/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.smokeping.middlewares: authelia@file

networks:
  reverse-proxy:
    external: true
