providers:
  docker:
    endpoint: tcp://docker:2375
    exposedByDefault: false
    network: traefik
    defaultRule: Host(`{{ index .Labels "com.docker.compose.service" }}.{{ env `NASCOMPOSE_TRAEFIK_DOMAIN` }}`)
  file:
    directory: /etc/traefik/dynamic/

serverstransport:
  insecureskipverify: true

api: {}
accessLog: {}

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    http:
      tls: {}
      middlewares:
        - hsts@file

global:
  sendAnonymousUsage: false
