name: Media-Player

services:
  plex:
    image: plexinc/pms-docker:plexpass
    environment:
      PLEX_UID: ${NASCOMPOSE_UID?}
      PLEX_GID: ${NASCOMPOSE_GID?}
    networks:
      - default
      - traefik
    volumes:
      - plex_transcode:/transcode/
      - plex_config:/config/
      - tv:/data/tv/
      - movies:/data/movies/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.services.plex.loadbalancer.server.port: 32400
      traefik.http.services.plex.loadbalancer.server.scheme: https

networks:
  traefik:
    external: true

volumes:
  movies:
    name: movies
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_DATA?}/media/movies/
  tv:
    name: tv
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_DATA?}/media/tv/

  plex_transcode:
  plex_config:
    driver_opts:
      type: none
      o: bind
      device: ${NASCOMPOSE_SERVICES?}/volumes/plex/config/
