# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  traefik:
    environment:
      NASCOMPOSE_MACVLAN_SYNOLOGY_IP: ${NASCOMPOSE_MACVLAN_HOST_IP?}
    networks:
      macvlan:
        ipv4_address: ${NASCOMPOSE_MACVLAN_TRAEFIK_IP?}

networks:
  macvlan:
    external: true
