name: irc

services:
  thelounge:
    hostname: thelounge
    image: lscr.io/linuxserver/thelounge
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - reverse-proxy
    dns:
      # Work around DNS blocks in various regions
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - ${NASCOMPOSE_SERVICES?}/irc/volumes/thelounge_config/:/config/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.thelounge.middlewares: authelia@file

networks:
  reverse-proxy:
    external: true
