# yaml-language-server: $schema=https://json.schemastore.org/traefik-v2-file-provider.json

http:
  middlewares:
    authelia:
      forwardAuth:
        address: http://authelia:9091/api/authz/forward-auth
        trustForwardHeader: true
        authResponseHeaders:
          - Authorization
          - Proxy-Authorization
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email
