http:
  middlewares:
    authelia:
      forwardAuth:
        address: http://authelia:9091/api/authz/forward-auth
        trustForwardHeader: true
        authResponseHeaders:
          - Authorization
          - Proxy-Authorization
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email
