http:
  middlewares:
    hsts:
      headers:
        customFrameOptionsValue: SAMEORIGIN
        browserXssFilter: true
        stsSeconds: 31536000 # 1 year
        stsPreload: true
        stsIncludeSubdomains: true
