http:
  routers:
    synology:
      rule: '{{ $s := "synology" }}{{ range $i, $d := splitList "," (env `NASCOMPOSE_TRAEFIK_DOMAINS`) }}{{ if $i }} || {{end}}Host(`{{ $s }}.{{ $d }}`){{ end }}'
      service: synology@file
  services:
    synology:
      loadBalancer:
        servers:
          - url: https://{{ env `NASCOMPOSE_MACVLAN_SYNOLOGY_IP` }}:5001/
