name: Portal

services:
  heimdall:
    hostname: heimdall
    image: lscr.io/linuxserver/heimdall
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - reverse-proxy
    volumes:
      - ${NASCOMPOSE_SERVICES?}/portal/volumes/heimdall_config/:/config/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.heimdall.middlewares: authelia@file

networks:
  reverse-proxy:
    external: true
