#!/command/with-contenv bash

echo "Obtaining Wireguard Server IP..."
wgserver=$(grep Endpoint "${CONFIG_DIR}/wireguard/wg0.conf" | awk '{print $3}')
echo "IP: ${wgserver%:*}"

echo "Obtaining default gateway..."
gateway=$(ip -o -4 route show to default | awk '{print $3}')
echo "Gateway: ${gateway}"

echo "Adding route to Wireguard Server via Default Gateway"
ip route add ${wgserver%:*}/32 via ${gateway} dev eth0
