name: photo-collector

services:
  immich:
    hostname: immich
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "immich" ]
    environment:
      DB_HOSTNAME: immich_postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE_NAME: immich
    networks:
      - reverse-proxy
      - default
    depends_on:
      - redis
      - database
    volumes:
      - ${NASCOMPOSE_DATA?}/media/photos/:/usr/src/app/upload/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.immich.middlewares: authelia@file

  immich-microservices:
    hostname: immich-microservices
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "microservices" ]
    depends_on:
      - redis
      - database
    volumes:
      - ${NASCOMPOSE_DATA?}/media/photos/:/usr/src/app/upload/
    restart: unless-stopped

  immich-machine-learning:
    hostname: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${NASCOMPOSE_SERVICES?}/photo-collector/volumes/imich_ml_cache/:/cache/
    restart: unless-stopped

  redis:
    image: redis
    hostname: redis
    restart: unless-stopped

  immich_postgres:
    hostname: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - ${NASCOMPOSE_SERVICES?}/photo-collector/volumes/immich_postgres_data/:/var/lib/postgresql/data/
    restart: unless-stopped
