name: Movie collector

services:
  radarr:
    hostname: radarr
    image: linuxserver/radarr
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - reverse-proxy
      - movie-collector
      - torrents
      - usenet
    volumes:
      - ${NASCOMPOSE_SERVICES?}/movie-collector/volumes/radarr_config/:/config/
      - ${NASCOMPOSE_DATA?}/:/data/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.middlewares: authelia@file

networks:
  movie-collector:
    name: movie-collector

  reverse-proxy:
    external: true
  torrents:
    external: true
  usenet:
    external: true
