name: notifiarr

services:
  notifiarr:
    hostname: notifiarr
    image: golift/notifiarr
    environment:
      PUID: ${NASCOMPOSE_UID?}
      PGID: ${NASCOMPOSE_GID?}
    networks:
      - reverse-proxy
    volumes:
      - ${NASCOMPOSE_SERVICES?}/notifiarr/volumes/notifiarr_config/:/config/
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.notifiarr.middlewares: authelia@file

  recyclarr:
    hostname: recyclarr
    image: ghcr.io/recyclarr/recyclarr
    user: ${NASCOMPOSE_UID?}:${NASCOMPOSE_GID?}
    networks:
      - reverse-proxy
    volumes:
      - ${NASCOMPOSE_SERVICES?}/notifiarr/volumes/recyclarr_config/:/config/
    restart: unless-stopped

networks:
  reverse-proxy:
    external: true
